name: Otus main
on:
  push:
    branches:
      - task_01
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: First print
        run: echo "Start!"
      - name: Checkout
        uses: actions/checkout@v4
      - run: gcc main.cpp -o helloworld
      - name: Create Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./helloworld-0.1.${{ github.run_number }}-Linux.deb
          asset_name: helloworld-0.1.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package
